# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
workflow:
  rules:
    - if: $CI_COMMIT_BRANCH != "main" && $CI_PIPELINE_SOURCE != "merge_request_event"
      when: never
    - when: always

stages:
- build
- test
- deploy
- review
- dast
- staging
- canary
- production
- incremental rollout 10%
- incremental rollout 25%
- incremental rollout 50%
- incremental rollout 100%
- performance
- cleanup

build_image:
  stage: build
  tags:
    - build
    - microservices
  variables:
    VERSION: $CI_COMMIT_REF_SLUG-$CI_PIPELINE_ID
    ADSERVICE_TAG: eshopimages.azurecr.io/eshop/adservice  
  script:
    - docker build -t $ADSERVICE_TAG:$VERSION src/adservice

sast:
  stage: test
include:
  - template: Auto-DevOps.gitlab-ci.yml

.build_image3:
  stage: build
  tags:
    - build
    - microservices
  variables:
    VERSION: $CI_PIPELINE_ID
    ADSERVICE_TAG: eshopimages.azurecr.io/eshop/adservice
  script:
    - bash script/docker-release.sh $ADSERVICE_TAG services src/adservice

.build_image2:
  stage: build
  tags:
    - build
    - microservices
  variables:
    DOCKER_REGISTRY: eshopimages.azurecr.io
  script:
    - docker login -u $ACR_USER -p $ACR_PASSWORD $DOCKER_REGISTRY

.build:
  stage: build
  tags:
    - build
    - microservices
  script:
    - echo "Building the Hello World application..."

.test:
  stage: test
  tags:
    - build
    - microservices
  script:
    - echo "Running tests for the Hello World application..."

