
IMAGE_TAG=$1
BUILD_CONTEXT=${2:-.}
DOCKER_FILE=${3:-Dockerfile}

docker login -u $ACR_USER -p $ACR_PASSWORD $DOCKER_REGISTRY
docker pull $IMAGE_TAG:$CI_COMMIT_REF_SLUG 
docker build --pull -f $DOCKER_FILE -t $IMAGE_TAG:$CI_COMMIT_REF_SLUG $BUILD_CONTEXT
docker tag $IMAGE_TAG:$CI_COMMIT_REF_SLUG $IMAGE_TAG:$VERSION
docker push $IMAGE_TAG:$CI_COMMIT_REF_SLUG
docker push $IMAGE_TAG:$VERSION
df -h